# Generated by Django 5.2.14 on 2026-05-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "学生"), ("admin", "管理员"), ("expert", "专家")],
                db_index=True,
                default="student",
                max_length=20,
                verbose_name="角色",
            ),
        ),
    ]
