# Generated by Django 5.2.14 on 2026-05-10 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="announcements/%Y/%m/",
                verbose_name="附件",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="body",
            field=models.TextField(verbose_name="正文"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="competitions.competition",
                verbose_name="竞赛",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="是否发布"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=255, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competitions_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="experts",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "expert"},
                related_name="assigned_competitions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评审专家",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="max_team_members",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="队伍人数上限"
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="registration_end",
            field=models.DateTimeField(verbose_name="报名截止时间"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="registration_start",
            field=models.DateTimeField(verbose_name="报名开始时间"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("published", "进行中"),
                    ("registration_closed", "报名已截止"),
                    ("reviewing", "评审中"),
                    ("finished", "已结束"),
                ],
                db_index=True,
                default="draft",
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="submission_deadline",
            field=models.DateTimeField(verbose_name="提交截止时间"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="title",
            field=models.CharField(max_length=255, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="competitions.competition",
                verbose_name="竞赛",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="competitions.team",
                verbose_name="队伍",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, verbose_name="评语"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="review",
            name="expert",
            field=models.ForeignKey(
                limit_choices_to={"role": "expert"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="专家",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="分数"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="competitions.submission",
                verbose_name="作品",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="submissions/%Y/%m/",
                verbose_name="附件",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="competitions.competition",
                verbose_name="竞赛",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="description",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="competitions.team",
                verbose_name="队伍",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="work_url",
            field=models.URLField(blank=True, verbose_name="作品链接"),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="team",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams_led",
                to=settings.AUTH_USER_MODEL,
                verbose_name="队长",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=255, verbose_name="队伍名称"),
        ),
        migrations.AlterField(
            model_name="team",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="joined_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="学生",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="competitions.team",
                verbose_name="队伍",
            ),
        ),
    ]
