# Generated by Django 5.2.14 on 2026-05-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_submission_attachments_remove_work_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('registering', '报名中'), ('published', '进行中'), ('registration_closed', '报名已截止'), ('reviewing', '评审中'), ('finished', '已结束')], db_index=True, default='draft', max_length=32, verbose_name='状态'),
        ),
    ]
